### ISSUE TITLE
Error on files with both IPTC:Keywords and XMP-dc:Subject set to single value

### ISSUE THREAD

**Issue by z-jun** [LycheeOrg/php-exif#37]
PHPExif is unable to parse file with both tags set  to single(parsed to string) value, at least with PHP8.

[----> see issue at Lychee](https://github.com/LycheeOrg/Lychee/issues/1237)

`[2022-03-03 02:50:12] production.ERROR: array_merge(): Argument https://github.com/LycheeOrg/Lychee/pull/1 must be of type array, string given {"exception":"[object] (TypeError(code: 0): array_merge(): Argument https://github.com/LycheeOrg/Lychee/pull/1 must be of type array, string given at /var/www/html/Lychee/vendor/lychee-org/php-exif/lib/PHPExif/Mapper/Exiftool.php:355)`

Hot fix:

```
--- ./vendor/lychee-org/php-exif/lib/PHPExif/Mapper/Exiftool.php.old    2022-03-12 23:33:35.454873706 +0100
+++ ./vendor/lychee-org/php-exif/lib/PHPExif/Mapper/Exiftool.php        2022-03-12 23:32:41.507807585 +0100
@@ -349,10 +349,11 @@
                 // Merge sources of keywords
                 case self::KEYWORDS:
                 case self::SUBJECT:
+                    $xval = is_array( $value) ? $value : array( 0 => $value);
                     if (empty($mappedData[Exif::KEYWORDS])) {
-                        $mappedData[Exif::KEYWORDS] = $value;
+                        $mappedData[Exif::KEYWORDS] = $xval;
                     } else {
-                        $tmp = array_values(array_unique(array_merge($mappedData[Exif::KEYWORDS], $value)));
+                        $tmp = array_values(array_unique(array_merge($mappedData[Exif::KEYWORDS], $xval)));
                         $mappedData[Exif::KEYWORDS] = $tmp;
                     }

```

**Comment by kamil4** [comment]
Thank you for the report and the fix! Would you mind posting a picture that triggers it? I want to check if this is something we need to fix for the native adapter as well...

**Comment by z-jun** [comment]
Try this one or make from any photy by `exiftool -Subject=bad -Keywords=bad some.jpg` 

![ok](https://user-images.githubusercontent.com/14344342/163283308-d5e9a597-8722-4bd8-85ff-2950e3695c19.jpg)

**Comment by kamil4** [comment]
Thank you! This should now be fixed!
